
#--------------------------------------------------------------------------------
log_parameters:
    #----------
    showtiming: True
    log_level : DEBUG
#--------------------------------------------------------------------------------
network_topology_parameters:
    #----------
    supernetwork_parameters:
        title_string: "Ngen"
        #----------
        network_type: HYFeaturesNetwork 
        geo_file_path: /Users/nelsfrazier/workspace/demo/camels_calibration/Gage_1022500.gpkg
        mask_file_path: # domain/unit_test_noRS/coastal_subset.txt
        synthetic_wb_segments:
            #- 4800002
            #- 4800004
            #- 4800006
            #- 4800007
        columns: 
            key: 'id'
            downstream: 'toid'
            dx : 'length_m'
            n : 'n'
            ncc : 'nCC'
            s0 : 'So'
            bw : 'BtmWdth'
            waterbody : 'rl_NHDWaterbodyComID'
            gages : 'rl_gages'
            tw : 'TopWdth'
            twcc : 'TopWdthCC'
            musk : 'MusK'
            musx : 'MusX'
            cs : 'ChSlp'
            alt: 'alt'
    waterbody_parameters:
        #----------
        break_network_at_waterbodies: False 
        level_pool:
            #----------
            level_pool_waterbody_parameter_file_path: /Users/nelsfrazier/workspace/demo/camels_calibration/Gage_1022500.gpkg
        #rfc:
            #----------
            #reservoir_parameter_file                : domain/reservoir_index_AnA.nc
            #reservoir_rfc_forecasts                 : False
            #reservoir_rfc_forecasts_time_series_path: rfc_TimeSeries/
            #reservoir_rfc_forecasts_lookback_hours  : 48
#--------------------------------------------------------------------------------
compute_parameters:
    #----------
    parallel_compute_method: by-subnetwork-jit-clustered #serial 
    compute_kernel         : V02-structured
    assume_short_ts        : True
    subnetwork_target_size : 10000
    cpu_pool               : 1
    restart_parameters:
        #----------
        start_datetime: "2018-01-01 00:00:00"
    forcing_parameters:
        #----------
        qts_subdivisions            : 12
        dt                          : 300 # [sec]
        qlat_input_folder           : ./ 
        qlat_file_pattern_filter    : "nex-*"
        binary_nexus_file_folder    : ./ # this is required if qlat_file_pattern_filter="nex-*"
        nts                         : 288 #288 for 1day
        max_loop_size               : 288 # [hr]  
    data_assimilation_parameters:
    #    #----------
    #    usgs_timeslices_folder   : #usgs_TimeSlice/
    #    usace_timeslices_folder  : #usace_TimeSlice/
    #    timeslice_lookback_hours : #48 
    #    qc_threshold             : #1
        streamflow_da:
    #        #----------
            streamflow_nudging            : False
            diffusive_streamflow_nudging  : False
        reservoir_da:
            #----------
            reservoir_persistence_da:
                #----------
                reservoir_persistence_usgs  : False
                reservoir_persistence_usace : False
            reservoir_rfc_da:
                #----------
                reservoir_rfc_forecasts: False
#--------------------------------------------------------------------------------
output_parameters:
    csv_output:
        csv_output_folder: ./
    #----------
